require:
  - solidus_dev_support/rubocop

AllCops:
  NewCops: enable

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rspec/RemoveConst:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
